#################################################
# Docker and Docker Compose Installation
#################################################
---

- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:

  - name: Download script
    get_url:
      url: https://get.docker.com/
      dest: /root/install_docker.sh
      mode: 0700

  - name: Install Docker
    shell: /root/install_docker.sh

  - name: Remove script
    file:
      state: absent
      path: /root/install_docker.sh

  - name: Start and enable Docker daemon
    service:
      name: docker
      state: started
      enabled: yes
      masked: no

  - name: Download and install Docker Compose
    get_url:
      url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 0755

  - name: Add user to the "docker" group
    user:
      name: "{{ user }}"
      groups: docker
      append: yes

  - name: Create a symbolic link
    file: src=/usr/local/bin/docker-compose dest=/usr/bin/docker-compose state=link

  - name: Reboot machine
    reboot:
